version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: master_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs,secretsmanager
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./scripts/init-localstack.sh:/docker-entrypoint-initdb.d/init-localstack.sh
      - localstack-data:/tmp/localstack/data
    networks:
      - app-network

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - app-network

  metadata:
    build:
      context: .
      dockerfile: metadata/Dockerfile
    container_name: metadata
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    depends_on:
      - postgres
      - redis
      - localstack
      - minio
    networks:
      - app-network

  data:
    build:
      context: .
      dockerfile: data/Dockerfile
    container_name: data
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    depends_on:
      - postgres
      - redis
      - localstack
      - minio
    networks:
      - app-network

  attachment:
    build:
      context: .
      dockerfile: attachment/Dockerfile
    container_name: attachment
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    depends_on:
      - postgres
      - redis
      - localstack
      - minio
    networks:
      - app-network

  user-management:
    build:
      context: .
      dockerfile: user-management/Dockerfile
    container_name: user-management
    ports:
      - "8084:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    depends_on:
      - postgres
      - redis
      - localstack
      - minio
    networks:
      - app-network

  report:
    build:
      context: .
      dockerfile: report/Dockerfile
    container_name: report
    ports:
      - "8085:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    depends_on:
      - postgres
      - redis
      - localstack
      - minio
    networks:
      - app-network

  audit:
    build:
      context: .
      dockerfile: audit/Dockerfile
    container_name: audit
    ports:
      - "8086:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    depends_on:
      - postgres
      - redis
      - localstack
      - minio
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
  localstack-data:
  minio-data:

