# QA environment configuration
spring:
  datasource:
    master:
      url: jdbc:postgresql://qa-postgres:5432/master_db
      username: postgres
      password: postgres
  
  # Enable Redis in QA mode
  redis:
    enabled: true
    host: qa-redis
  
  # Enable Kafka in QA mode
  kafka:
    enabled: true
    bootstrap-servers: qa-kafka:9092

# AWS services use QA endpoints
aws:
  region: us-east-1
  s3:
    endpoint: https://s3.us-east-1.amazonaws.com
    bucket-name: qa-multi-tenant-bucket
  sqs:
    endpoint: https://sqs.us-east-1.amazonaws.com
    queue-name: qa-multi-tenant-queue
  secretsmanager:
    endpoint: https://secretsmanager.us-east-1.amazonaws.com

# Use AWS S3 in QA
minio:
  enabled: false

# Logging configuration for QA
logging:
  level:
    com.example: INFO
    org.springframework: INFO
    org.hibernate.SQL: INFO

