spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://qa-db-host:5432/master_db
    username: postgres
    password: postgres

# QA environment specific settings
aws:
  enabled: true
  region: us-east-1
  sqs:
    enabled: true
  s3:
    enabled: true
  secretsmanager:
    enabled: true
  
redis:
  enabled: true
  host: qa-redis-host
  port: 6379
  
kafka:
  enabled: true
  bootstrap-servers: qa-kafka-host:9092

