spring:
  datasource:
    master:
      url: jdbc:postgresql://dev-postgres:5432/master_db
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  data:
    redis:
      enabled: true
      host: dev-redis
      port: 6379
      password: ${REDIS_PASSWORD}
  kafka:
    enabled: true
    bootstrap-servers: dev-kafka:9092

aws:
  region: ${AWS_REGION:us-east-1}
  s3:
    enabled: true
  sqs:
    enabled: true
  secretsmanager:
    enabled: true

logging:
  level:
    com.example: DEBUG
    org.springframework: INFO

