# Production environment configuration
spring:
  datasource:
    master:
      url: jdbc:postgresql://prod-postgres:5432/master_db
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      hikari:
        minimum-idle: 5
        maximum-pool-size: 20
        idle-timeout: 30000
        max-lifetime: 2000000
        connection-timeout: 30000
  
  # Enable Redis in production mode
  redis:
    enabled: true
    host: prod-redis
    password: ${REDIS_PASSWORD}
  
  # Enable Kafka in production mode
  kafka:
    enabled: true
    bootstrap-servers: prod-kafka:9092

# AWS services use production endpoints
aws:
  region: us-east-1
  s3:
    enabled: true
    endpoint: https://s3.us-east-1.amazonaws.com
    bucket-name: prod-multi-tenant-bucket
  sqs:
    enabled: true
    endpoint: https://sqs.us-east-1.amazonaws.com
    queue-name: prod-multi-tenant-queue
  secretsmanager:
    enabled: true
    endpoint: https://secretsmanager.us-east-1.amazonaws.com

# Disable Minio in production (use AWS S3)
minio:
  enabled: false

# Logging configuration for production
logging:
  level:
    root: WARN
    com.example: INFO
    org.springframework: WARN
    org.hibernate: WARN

