spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/master_db
    username: postgres
    password: postgres

# Local environment specific settings
aws:
  enabled: false
  
redis:
  enabled: false
  
kafka:
  enabled: false

