spring:
  datasource:
    master:
      url: jdbc:postgresql://qa-db-host:5432/master_db
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
      hikari:
        minimum-idle: 2
        maximum-pool-size: 10
        idle-timeout: 30000
        pool-name: MasterHikariPool

multitenancy:
  tenant-header: X-Tenant-ID
  tenant-parameter: tenantId
  default-tenant: default

redis:
  enabled: true
  host: qa-redis-host
  port: 6379
  password: ${REDIS_PASSWORD}
  database: 0
  timeout: 10000
  cache:
    enabled: true
    ttl: 3600

aws:
  enabled: true
  region: us-east-1
  s3:
    bucket: qa-bucket
  sqs:
    queue-url: https://sqs.us-east-1.amazonaws.com/123456789012/qa-queue
  secretsmanager:
    enabled: true

minio:
  enabled: false

logging:
  level:
    com.example: DEBUG
    org.springframework: INFO
    org.hibernate: INFO

