spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://prod-db-host:5432/master_db
    username: postgres
    password: postgres

# Production environment specific settings
aws:
  enabled: true
  region: us-east-1
  sqs:
    enabled: true
  s3:
    enabled: true
  secretsmanager:
    enabled: true
  
redis:
  enabled: true
  host: prod-redis-host
  port: 6379
  
kafka:
  enabled: true
  bootstrap-servers: prod-kafka-host:9092

