spring:
  datasource:
    master:
      url: jdbc:postgresql://localhost:5432/master_db
      username: ${DB_USERNAME:postgres}
      password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    enabled: false
  kafka:
    enabled: false

aws:
  s3:
    enabled: false
  sqs:
    enabled: false
  secretsmanager:
    enabled: false

minio:
  enabled: true
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  bucket-name: main-bucket
  schema-bucket-name: schema-bucket
  image-bucket-name: image-bucket
  flex-bucket-name: flex-bucket
  company-profile-bucket-name: profile-bucket
  data-management-bucket-name: data-bucket

logging:
  level:
    com.example: DEBUG
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

