# Development environment configuration
spring:
  datasource:
    master:
      url: jdbc:postgresql://dev-postgres:5432/master_db
      username: postgres
      password: postgres
  
  # Enable Redis in dev mode
  redis:
    enabled: true
    host: dev-redis
  
  # Enable Kafka in dev mode
  kafka:
    enabled: true
    bootstrap-servers: dev-kafka:9092

# AWS services use dev endpoints
aws:
  region: us-east-1
  s3:
    endpoint: https://s3.us-east-1.amazonaws.com
    bucket-name: dev-multi-tenant-bucket
  sqs:
    endpoint: https://sqs.us-east-1.amazonaws.com
    queue-name: dev-multi-tenant-queue
  secretsmanager:
    endpoint: https://secretsmanager.us-east-1.amazonaws.com

# Use dev Minio instance
minio:
  enabled: false  # Use AWS S3 instead in dev

# Logging configuration for dev
logging:
  level:
    com.example: DEBUG
    org.springframework: INFO
    org.hibernate.SQL: INFO

