spring:
  datasource:
    master:
      url: jdbc:postgresql://qa-postgres:5432/master_db
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  redis:
    enabled: true
    sentinel:
      master: mymaster
      nodes: qa-redis-sentinel-0:26379,qa-redis-sentinel-1:26379,qa-redis-sentinel-2:26379
    password: ${REDIS_PASSWORD}
  kafka:
    enabled: true
    bootstrap-servers: qa-kafka-0:9092,qa-kafka-1:9092,qa-kafka-2:9092

aws:
  region: ${AWS_REGION:us-east-1}
  s3:
    enabled: true
  sqs:
    enabled: true
  secretsmanager:
    enabled: true

logging:
  level:
    com.example: INFO
    org.springframework: INFO

