spring:
  application:
    name: multi-module-app
  profiles:
    active: local
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  datasource:
    master:
      url: jdbc:postgresql://localhost:5432/master
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
      hikari:
        minimum-idle: 2
        maximum-pool-size: 5
        idle-timeout: 30000
        pool-name: MasterHikariPool
        max-lifetime: 2000000
        connection-timeout: 30000

# Multi-tenant configuration
multitenancy:
  master:
    repository:
      packages: com.example.applib.tenant
    entity:
      packages: com.example.applib.tenant

# AWS Configuration
aws:
  region: us-east-1
  s3:
    bucket: app-bucket
  sqs:
    queue-url: https://sqs.us-east-1.amazonaws.com/123456789012/app-queue
  secretsmanager:
    enabled: true

# Redis Configuration
redis:
  enabled: true
  host: localhost
  port: 6379
  password: 
  timeout: 10000
  database: 0
  cache:
    enabled: true
    ttl: 3600
  pubsub:
    enabled: true
  queue:
    enabled: true

# Minio Configuration (S3 alternative for local development)
minio:
  enabled: false
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucket: app-bucket

# Logging
logging:
  level:
    root: INFO
    com.example: DEBUG
    org.springframework: INFO
    org.hibernate: INFO

# Server configuration
server:
  port: 8080
  servlet:
    context-path: /api

