apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  username: cG9zdGdyZXM=  # postgres (base64 encoded)
  password: cG9zdGdyZXM=  # postgres (base64 encoded)
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
type: Opaque
data:
  password: cmVkaXNwYXNzd29yZA==  # redispassword (base64 encoded)

